### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components (line 41)

### ISSUE THREAD

**Issue by siredwin** [robgolding/celery-s3#3]
Thanks for this project.

key = os.path.join(self.base_path, key)
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 145, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

**Comment by robgolding** [comment]
Hey @EdwinRor! Can you give some more context here? I'll need to see the code you're using to get an idea for what's going on. Thanks!

**Comment by siredwin** [comment]
I am actually referring to and using code from the main branch. I also have a local copy of it to make minor adjustments.

Perhaps you should tell me what the initial value of key in line 41 is? It seems to be None. I set it to `self.aws_access_key_id` and i no longer get any errors. The other option was set it to an empty string.

I also changed line 39 from `k = Key(self. s3_bucket)` to `k = Key(bucket=self.s3_bucket)`. It didn't seem to make a difference without it,  but i slept better.

What are the plans for this project?

**Comment by thearod5** [comment]
I am getting this error again, was there any real indication of what was going wrong?
